name: Deploy to Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod
      image_tag:
        description: 'Image tag to deploy (leave empty for latest)'
        required: false
        type: string
        default: ''

env:
  AWS_REGION: eu-central-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set image tag
      id: image_tag
      run: |
        if [[ -n "${{ github.event.inputs.image_tag }}" ]]; then
          echo "tag=${{ github.event.inputs.image_tag }}" >> $GITHUB_OUTPUT
        else
          # Get latest tag from ECR for Client
          LATEST_TAG=$(aws ecr describe-images \
            --repository-name booking-client \
            --region ${{ env.AWS_REGION }} \
            --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' \
            --output text)
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
        fi
        echo "Using Client image tag: ${{ steps.image_tag.outputs.tag }}"
        
        # Get ECR registry URL
        ECR_REGISTRY=$(aws ecr describe-registry --region ${{ env.AWS_REGION }} --query 'registryId' --output text).dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        echo "ecr_registry=$ECR_REGISTRY" >> $GITHUB_OUTPUT

    - name: Update ECS Service
      run: |
        echo "Updating ECS service with new image..."
        
        # Get ECS cluster name
        CLUSTER_NAME="booking-app-${{ github.event.inputs.environment }}"
        SERVICE_NAME="booking-client-${{ github.event.inputs.environment }}"
        
        # Get current task definition
        TASK_DEFINITION_ARN=$(aws ecs describe-services \
          --cluster "$CLUSTER_NAME" \
          --services "$SERVICE_NAME" \
          --region ${{ env.AWS_REGION }} \
          --query 'services[0].taskDefinition' \
          --output text)
        
        echo "Current task definition: $TASK_DEFINITION_ARN"
        
        # Get task definition details
        TASK_DEFINITION=$(aws ecs describe-task-definition \
          --task-definition "$TASK_DEFINITION_ARN" \
          --region ${{ env.AWS_REGION }} \
          --query 'taskDefinition')
        
        # Extract only required fields for new task definition
        NEW_TASK_DEFINITION=$(echo "$TASK_DEFINITION" | jq '{
          family: .family,
          taskRoleArn: .taskRoleArn,
          executionRoleArn: .executionRoleArn,
          networkMode: .networkMode,
          containerDefinitions: .containerDefinitions,
          volumes: .volumes,
          placementConstraints: .placementConstraints,
          requiresCompatibilities: .requiresCompatibilities,
          cpu: .cpu,
          memory: .memory
        } | if .tags == null then del(.tags) else . end')
        
        # Update image URL in container definitions
        UPDATED_TASK_DEFINITION=$(echo "$NEW_TASK_DEFINITION" | jq --arg image "${{ steps.image_tag.outputs.ecr_registry }}/booking-client:${{ steps.image_tag.outputs.tag }}" '.containerDefinitions[0].image = $image')
        
        # Get secrets from Secrets Manager and add them to task definition
        echo "Getting secrets from Secrets Manager..."
        
        # Get API base URL secret ARN
        API_BASE_URL_ARN=$(aws secretsmanager describe-secret \
          --secret-id "dev/booking-client/api-base-url" \
          --region ${{ env.AWS_REGION }} \
          --query 'ARN' \
          --output text)
        
        # Get JWT secret ARN
        JWT_SECRET_ARN=$(aws secretsmanager describe-secret \
          --secret-id "dev/booking-client/jwt-secret" \
          --region ${{ env.AWS_REGION }} \
          --query 'ARN' \
          --output text)
        
        # Get Telegram bot token ARN
        TELEGRAM_BOT_TOKEN_ARN=$(aws secretsmanager describe-secret \
          --secret-id "dev/booking-client/telegram-bot-token" \
          --region ${{ env.AWS_REGION }} \
          --query 'ARN' \
          --output text)
        
        echo "API_BASE_URL_ARN: $API_BASE_URL_ARN"
        echo "JWT_SECRET_ARN: $JWT_SECRET_ARN"
        echo "TELEGRAM_BOT_TOKEN_ARN: $TELEGRAM_BOT_TOKEN_ARN"
        
        # Create secrets array for task definition
        SECRETS_JSON=$(jq -n --arg api_arn "$API_BASE_URL_ARN" --arg jwt_arn "$JWT_SECRET_ARN" --arg telegram_arn "$TELEGRAM_BOT_TOKEN_ARN" '[
          {
            "name": "API_BASE_URL",
            "valueFrom": $api_arn
          },
          {
            "name": "JWT_SECRET", 
            "valueFrom": $jwt_arn
          },
          {
            "name": "TELEGRAM_BOT_TOKEN",
            "valueFrom": $telegram_arn
          }
        ]')
        
        echo "Secrets JSON: $SECRETS_JSON"
        
        # Add secrets to task definition
        UPDATED_TASK_DEFINITION=$(echo "$UPDATED_TASK_DEFINITION" | jq --argjson secrets "$SECRETS_JSON" '.containerDefinitions[0].secrets = $secrets')
        
        # Register new task definition
        NEW_TASK_DEFINITION_ARN=$(aws ecs register-task-definition \
          --cli-input-json "$UPDATED_TASK_DEFINITION" \
          --region ${{ env.AWS_REGION }} \
          --query 'taskDefinition.taskDefinitionArn' \
          --output text)
        
        echo "New task definition: $NEW_TASK_DEFINITION_ARN"
        
        # Update service
        aws ecs update-service \
          --cluster "$CLUSTER_NAME" \
          --service "$SERVICE_NAME" \
          --task-definition "$NEW_TASK_DEFINITION_ARN" \
          --region ${{ env.AWS_REGION }}
        
        echo "ECS service updated successfully!"

    - name: Wait for Service Update
      run: |
        echo "Waiting for service to stabilize..."
        CLUSTER_NAME="booking-app-${{ github.event.inputs.environment }}"
        SERVICE_NAME="booking-client-${{ github.event.inputs.environment }}"
        
        aws ecs wait services-stable \
          --cluster "$CLUSTER_NAME" \
          --services "$SERVICE_NAME" \
          --region ${{ env.AWS_REGION }}
        
        echo "Service is stable!"

    - name: Deployment Summary
      run: |
        echo "## Deployment Completed Successfully!"
        echo ""
        echo "**Environment:** ${{ github.event.inputs.environment }}"
        echo "**Image Tag:** ${{ steps.image_tag.outputs.tag }}"
        echo "**Service:** booking-client-${{ github.event.inputs.environment }}"
        echo ""
        echo "### Next Steps:"
        echo "1. Deployment completed"
        echo "2. Service is stable"
        echo "3. Monitor logs if needed"
        echo "4. Ready for use!"